label: Media
display:
  default:
    display_title: Master
    display_options:
      title: Media
      fields:
        thumbnail__target_id:
          label: Thumbnail
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: 'Media type'
          separator: ', '
        uid:
          label: Author
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_false: Unpublished
            format_custom_true: 'تم النشر'
          separator: ', '
        changed:
          label: Changed
          separator: ', '
        operations:
          label: Operations
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
      filters:
        bundle:
          expose:
            label: 'Media type'
        status:
          expose:
            label: 'True'
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: 'تم النشر'
              2:
                title: Unpublished
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
