ncms_publisher.publisher.*:
  type: config_entity
  label: 'Publisher config'
  mapping:
    id:
      type: string
      label: 'ID'
      constraints:
        NotNull: []
    label:
      type: label
      label: 'Label'
    known_hosts:
      type: text
      label: 'ID'
    uuid:
      type: string
      constraints:
        Uuid: []
