# Formatters.
field.formatter.settings.gho_article_list:
  type: mapping
  label: 'GHO article list formatter settings'
  mapping: {  }
    # No settings.
field.formatter.settings.gho_caption:
  type: mapping
  label: 'GHO caption formatter settings'
  mapping: {  }
    # No settings.
field.formatter.settings.gho_dataset_link:
  type: mapping
  label: 'GHO dataset link formatter settings'
  mapping: {  }
    # No settings.
field.formatter.settings.gho_interactive_content:
  type: mapping
  label: 'GHO interactive content formatter settings'
  mapping: {  }
    # No settings.
field.formatter.settings.gho_further_reading_link:
  type: mapping
  label: 'GHO further reading link formatter settings'
  mapping: {  }
    # No settings.
field.formatter.settings.gho_number:
  type: mapping
  label: 'GHO number formatter settings'
  mapping:
    format:
      type: string
      label: 'Format'
    precision:
      type: integer
      label: 'Precision'
field.formatter.settings.gho_related_articles:
  type: mapping
  label: 'GHO related articles formatter settings'
field.formatter.settings.gho_figures:
  type: mapping
  label: 'GHO figures formatter settings'
  mapping:
    format:
      type: string
      label: 'Format'

# Widgets.
field.widget.settings.gho_dataset_link:
  # Inherit the settings from the link widget.
  type: field.widget.settings.link_default
  label: 'GHO dataset link widget settings'
field.widget.settings.gho_interactive_content:
  # Inherit the settings from the textarea widget.
  type: field.widget.settings.string_textarea
  label: 'GHO interactive content widget settings'
field.widget.settings.gho_further_reading_link:
  # Inherit the settings from the link widget.
  type: field.widget.settings.link_default
  label: 'GHO further reading link widget settings'
field.widget.settings.gho_menu_select:
  type: mapping
  label: 'GHO menu select widget settings'
  mapping: {  }
    # No settings.
