label: Content
description: 'Find and manage content.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        title:
          label: Title
        type:
          label: 'Content type'
        changed:
          label: Changed
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        status:
          expose:
            label: Status
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: Publié
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
      title: Content
      empty:
        area_text_custom:
          content: 'No content available.'
    display_title: Master
