_core:
  default_config_hash: ZKVq7lpyGFQf-SCuj_Ng2yLPD24rKHxz-TzGQxBjLl4
paths:
  - '*'
  - ~user/login
  - '~user/login/*'
  - ~openid-connect/entraid
  - ~ncms
  - ~ncms/login
  - ~media/oembed
  - ~json/health-check-results
login_path: /ncms/login
message: ''
