_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_denied: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  anonymous_login: 0
  bigint: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_config: 0
  components: 0
  config: 0
  config_translation: 0
  contextual: 0
  csp: 0
  ctools: 0
  double_field: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  gho_access: 0
  gho_download: 0
  gho_fields: 0
  gho_figures: 0
  gho_footnotes: 0
  gho_general: 0
  gho_graphql: 0
  gho_layouts: 0
  google_tag: 0
  graphql: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_binaries: 0
  imagemagick: 0
  inline_entity_form: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  linked_responsive_image_media_formatter: 0
  locale: 0
  maintenance200: 0
  media: 0
  media_library: 0
  memcache: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  mysql: 0
  ncms_publisher: 0
  ncms_ui: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_viewmode: 0
  path: 0
  path_alias: 0
  redirect: 0
  responsive_image: 0
  search: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  sophron: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  typed_data: 0
  update: 0
  user: 0
  user_expire: 0
  views_ui: 0
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  common_design: 0
  common_design_subtheme: 0
  seven: 0
  common_design_admin_subtheme: 0
profile: minimal
