_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  'admin_toolbar_tools__extra_links:node__add':
    menu_name: admin
    parent: system.admin_content
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:node__add__achievement':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:node__add__article':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:node__add__document':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:node__add__story':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
    enabled: false
