_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
report-only:
  enable: true
  directives:
    connect-src:
      base: self
      sources:
        - gov-bam.nr-data.net
        - www.google-analytics.com
        - '*.doubleclick.net'
        - '*.analytics.google.com'
    font-src:
      base: self
      sources:
        - 'data:'
        - gho.unocha.org
        - fonts.gstatic.com
    img-src:
      base: self
      sources:
        - stats.datawrapper.de
        - www.googletagmanager.com
        - www.gstatic.com
        - translate.google.com
        - www.google-analytics.com
    object-src:
      base: none
    script-src:
      base: self
      sources:
        - js-agent.newrelic.com
        - fonts.googleapis.com
        - www.gstatic.com
        - www.google.com
        - www.googletagmanager.com
        - www.google-analytics.com
    script-src-attr:
      base: self
    script-src-elem:
      base: self
      flags:
        - unsafe-inline
    style-src:
      base: self
      sources:
        - translate.googleapis.com
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
enforce:
  enable: true
  directives:
    object-src:
      base: none
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
