_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - media
operations_enabled_entity_types: {  }
track_enabled_source_entity_types:
  - file
  - media
  - node
  - paragraph
  - taxonomy_term
track_enabled_target_entity_types:
  - media
track_enabled_plugins:
  - block_field
  - ckeditor_image
  - custom_field
  - dynamic_entity_reference
  - entity_embed
  - entity_reference
  - file_field
  - html_link
  - layout_builder
  - link
  - linkit
  - media_embed
track_enabled_base_fields: true
ignore_media_thumbnails: true
site_domains: {  }
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types: {  }
usage_controller_items_per_page: 25
