_core:
  default_config_hash: 0E8z47ONguVcapiw1PGWDRs6g0NRDCzrym4mP_jcELU
auth:
  social_auth_google:
    route: social_auth_google.redirect_to_google
    img_path: modules/contrib/social_auth_google/img/google_logo.svg
post_login: /
user_allowed: login
redirect_user_form: false
disable_admin_login: true
disabled_roles:
  administrator: '0'
uuid: b6aa421e-fe66-4609-84e8-ac2f95e11dd0
